# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42f526fc0b786b94fd993c8b8bfbd77d91485efeedf5d4ce9830ce9ca44c6108ef2dcd24e5bfe87947e0adb14e2a24ca15ff53c0a2cc6cfe07bcb5e7abbf86f6

test:
  secret_key_base: 98b9a6e5c847b2dd0650fb67cd5ef649b762fc776a7eeb7026e46270f47a2da89dc9a33050c5784ab6f254d28f0aa0959390c2a3592efee01ee0fb66294b91eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
